name: Build and Deploy to Cloud Run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
        gcloud config set run/region us-central1

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 256M


    - name: Handle Error
      if: ${{ failure() }}
      run: |
        echo "Error occurred. Performing specific task."
        repo_name="$(basename $GITHUB_REPOSITORY)"
        commit_name="${{ github.event.head_commit.message }}"
        error_failure="${{ job.status == 'failure' }}"
        curl -X POST -H "Content-Type: application/json" -d '{"EventName":"","OccurredAt":"","value1":"<h1>DEVOPS DEPLOYMENT REPOSITORY: '"$repo_name"' FAILURE</h1>","value2":"<h2>Git Commit - '"$commit_name"'</h2>","value3":"ERROR: '"$error_failure"'"}' "https://maker.ifttt.com/trigger/devopscicd/with/key/${{ secrets.IFTTT_KEY }}"

    - name: Final Step
      run: |
        echo "Final step"
        repo_name="$(basename $GITHUB_REPOSITORY)"
        commit_name="${{ github.event.head_commit.message }}"
        error_failure="${{ job.status == 'failure' }}"
        curl -X POST -H "Content-Type: application/json" -d '{"EventName":"","OccurredAt":"","value1":"<h1>DEVOPS DEPLOYMENT REPOSITORY: '"$repo_name"'</h1>","value2":"<h2>Git Commit - '"$commit_name"'</h2>","value3":"ERROR: '"$error_failure"'"}' "https://maker.ifttt.com/trigger/devopscicd/with/key/${{ secrets.IFTTT_KEY }}"
